baseURL = "https://flonam.nl/"
title = "Flonam B.V."
languageCode = "nl"
defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = false
timeZone = "Europe/Amsterdam"

[languages]
  [languages.nl]
    languageName = "Nederlands"
    weight = 1
    contentDir = "content/nl"

[pagination]
  pagerSize = 12

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[outputs]
  home = ["HTML", "RSS"]

[params]
  description = "SaaS-tools voor B2B-teams die efficiënter willen werken en processen willen versnellen. Gebouwd op ervaring in digitale toegankelijkheid."
  author = "Flonam B.V."
  logoText = "Flonam B.V."

  [params.contact]
    email = "info@flonam.nl"

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menus.main]]
    name = "Over ons"
    url = "/over/"
    weight = 2
  [[menus.main]]
    name = "Diensten"
    url = "/diensten/"
    weight = 3
  [[menus.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
