baseURL = "https://flonam.nl/"
title = "Flonam"
languageCode = "nl"
defaultContentLanguage = "nl"
defaultContentLanguageInSubdir = false
timeZone = "Europe/Amsterdam"

[languages]
  [languages.nl]
    label = "Nederlands"
    weight = 1
    contentDir = "content/nl"
    [languages.nl.params]
      description = "Wij bouwen SaaS-oplossingen voor bedrijven en organisaties."
    [[languages.nl.menus.main]]
      name = "Home"
      url = "/"
      weight = 1
    [[languages.nl.menus.main]]
      name = "Over ons"
      url = "/over/"
      weight = 2
    [[languages.nl.menus.main]]
      name = "Producten"
      url = "/producten/"
      weight = 3
    [[languages.nl.menus.main]]
      name = "Contact"
      url = "/contact/"
      weight = 4
  [languages.en]
    label = "English"
    weight = 2
    contentDir = "content/en"
    [languages.en.params]
      description = "We build SaaS solutions for businesses and organisations."
    [[languages.en.menus.main]]
      name = "Home"
      url = "/en/"
      weight = 1
    [[languages.en.menus.main]]
      name = "About us"
      url = "/en/about/"
      weight = 2
    [[languages.en.menus.main]]
      name = "Products"
      url = "/en/products/"
      weight = 3
    [[languages.en.menus.main]]
      name = "Contact"
      url = "/en/contact/"
      weight = 4

[pagination]
  pagerSize = 12

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'

[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[outputs]
  home = ["HTML", "RSS"]

[params]
  author = "Flonam"
  logoText = "Flonam"

  [params.contact]
    email = "info@flonam.nl"
    address = "Randweg 25, 8304 AS Emmeloord"
    kvk = "42103028"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
